apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: itn-2026-00040-rhwa-fbc-412-prod-20260305-0957
  namespace: rhwa-tenant
spec:
  releasePlan: rhwa-fbc-412-releaseplan-prod
  snapshot: rhwa-fbc-412-20260220-145603-000
