apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhwa-25-9-fbc-419-prod-ga
  namespace: rhwa-tenant
spec:
  releasePlan: rhwa-fbc-419-releaseplan-prod
  snapshot: rhwa-fbc-419-mkff2
