apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: snr-0-10-1-fbc-417-prod-ga
  namespace: rhwa-tenant
spec:
  releasePlan: snr-0-10-fbc-417-releaseplan-prod
  snapshot: snr-0-10-fbc-417-dc6cz
