apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: snr-0-9-1-prod-ga
  namespace: rhwa-tenant
spec:
  releasePlan: snr-0-9-releaseplan-prod
  snapshot: snr-0-9-zjs67
  data:
    releaseNotes:
      type: RHBA
      issues: 
        fixed:
          - id: RHWA-13
            source: issues.redhat.com
          - id: ECOPROJECT-2642
            source: issues.redhat.com
      references:
       - https://docs.redhat.com/en/documentation/workload_availability_for_red_hat_openshift/25.3