apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhwa-25-4-fbc-415-prod-ga
  namespace: rhwa-tenant
spec:
  releasePlan: nmo-5-4-fbc-415-releaseplan-prod
  snapshot: nmo-5-4-fbc-415-rtbjq
