apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhwa-25.7-fbc-419-prod-ga
  namespace: rhwa-tenant
spec:
  releasePlan: nhc-0-9-fbc-419-releaseplan-prod
  snapshot: nhc-0-9-fbc-419-wdlr8
