# The base image is expected to contain /bin/opm and it is a dummy catalog file from SNR stable graphs
FROM registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.19

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

ADD containers/catalog /configs
RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

# Set specific label for the location of the declarative config root directory in the image
LABEL operators.operatorframework.io.index.configs.v1=/configs
