apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: nhc-0-10-0-prod-ga
  namespace: rhwa-tenant
spec:
  releasePlan: nhc-0-10-releaseplan-prod
  snapshot: nhc-0-10-kmtg2
  data:
    releaseNotes:
      type: RHBA
      issues: 
        fixed:
          - id: RHWA-10
            source: issues.redhat.com
          - id: RHWA-11
            source: issues.redhat.com
          - id: RHWA-62
            source: issues.redhat.com
          - id: RHWA-66
            source: issues.redhat.com
          - id: RHWA-88
            source: issues.redhat.com
          - id: RHWA-255
            source: issues.redhat.com
          - id: RHWA-264
            source: issues.redhat.com
          - id: RHWA-269
            source: issues.redhat.com
          - id: RHWA-275
            source: issues.redhat.com
          - id: RHWA-278
            source: issues.redhat.com
      references:
       - https://docs.redhat.com/en/documentation/workload_availability_for_red_hat_openshift/25.8
