apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhwa-25-8-fbc-416-prod-ga
  namespace: rhwa-tenant
spec:
  releasePlan: rhwa-fbc-416-releaseplan-prod
  snapshot: rhwa-fbc-416-l494m
