apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: hotfix-cap910-rhwa-fbc-418-hotfix-prod-20260212-1442
  namespace: rhwa-tenant
spec:
  releasePlan: rhwa-fbc-418-releaseplan-prod-hotfix
  snapshot: rhwa-fbc-418-hotfix-20260209-144325-000
