apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhwa-25.6-mdr-0-4-fbc-415-prod-ga
  namespace: rhwa-tenant
spec:
  releasePlan: mdr-0-4-fbc-415-releaseplan-prod
  snapshot: mdr-0-4-fbc-415-b25rg
