apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: mdr-0-7-0-prod
  namespace: rhwa-tenant
spec:
  releasePlan: mdr-0-7-releaseplan-prod
  snapshot: mdr-0-7-20260527-075052-000
  data:
    releaseNotes:
      type: RHEA
      issues:
        fixed:
          - id: RHWA-514
            source: issues.redhat.com
          - id: RHWA-295
            source: issues.redhat.com
          - id: RHWA-475
            source: issues.redhat.com
          - id: RHWA-885
            source: issues.redhat.com
