apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhwa-4.22-0-rhwa-fbc-422-prod-20260616-0931
  namespace: rhwa-tenant
spec:
  releasePlan: rhwa-fbc-422-releaseplan-prod
  snapshot: rhwa-fbc-422-20260529-075731-000
