apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: hotfix-cap910-420-fbc-prod-20260212-1416
  namespace: rhwa-tenant
spec:
  releasePlan: rhwa-fbc-420-releaseplan-prod-hotfix
  snapshot: rhwa-fbc-420-hotfix-20260205-152623-000
