apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhwa-658-fbc-421-prod
  namespace: rhwa-tenant
spec:
  releasePlan: rhwa-fbc-421-releaseplan-prod
  snapshot: rhwa-fbc-421-8b8k2
