apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: far-0-6-1-prod
  namespace: rhwa-tenant
spec:
  releasePlan: far-0-6-releaseplan-prod
  snapshot: far-0-6-20260130-175809-000
  data:
    releaseNotes:
      type: RHEA
      issues:
        fixed:
          - id: RHWA-781
            source: issues.redhat.com
