apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhwa-25.5-fbc-414-prod-ga
  namespace: rhwa-tenant
spec:
  releasePlan: far-0-5-fbc-414-releaseplan-prod
  snapshot: far-0-5-fbc-414-tf86c
