apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: far-0-7-0-prod
  namespace: rhwa-tenant
spec:
  releasePlan: far-0-7-releaseplan-prod
  snapshot: far-0-7-20260223-123454-000
  data:
    releaseNotes:
      type: RHEA
      issues: 
        fixed:
          - id: RHWA-65
            source: issues.redhat.com
          - id: RHWA-613
            source: issues.redhat.com
          - id: RHWA-311
            source: issues.redhat.com
          - id: RHWA-364
            source: issues.redhat.com
          - id: RHWA-512
            source: issues.redhat.com
